name: paint_canvas
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_drawing_board: ^0.9.8
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #     - asset: assets/fonts/Poppins-Italic.ttf
  #       style: italic
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Poppins-Light.ttf
  #       weight: 300
  #     - asset: assets/fonts/Poppins-ExtraLight.ttf
  #       weight: 200
  #     - asset: assets/fonts/Poppins-Black.ttf
