name: canvaz
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  flutter_drawing_board: ^0.9.8
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.14.4
  path_provider: ^2.1.1
  signature: ^6.3.0
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: trueß
  image_path: "assets/icons/canvaz.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/canvaz.png"
  windows:
    generate: true
    image_path: "assets/icons/canvaz.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/canvaz.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #     - asset: assets/fonts/Poppins-Italic.ttf
  #       style: italic
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 700
  #     - asset: assets/fonts/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Poppins-Light.ttf
  #       weight: 300
  #     - asset: assets/fonts/Poppins-ExtraLight.ttf
  #       weight: 200
  #     - asset: assets/fonts/Poppins-Black.ttf
